hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    city-service:
        path: /city/**
        serviceId: city-service
        stripPrefix: false
        sensitiveHeaders:

    route-service:
        path: /route/**
        serviceId: route-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
